package com.mycompany.musicchart;

import javax.swing.JTable;
import javax.swing.table.*;

public class MainMenu extends javax.swing.JFrame {
    Genie rg = new Genie();
    Melon rm = new Melon();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        SearchMelon = new javax.swing.JButton();
        SearchGenie = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel2.setText("제목");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Melon");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Genie");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        SearchMelon.setText("Search Melon");
        SearchMelon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMelonActionPerformed(evt);
            }
        });

        SearchGenie.setText("Search Genie");
        SearchGenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchGenieActionPerformed(evt);
            }
        });

        jLabel1.setText("가수");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jButton3)))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchMelon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchGenie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(SearchMelon))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchGenie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm;
        JTable table;
        Object[][] rowData = new Object[50][3];
        
        for(int i = 0; i < 50; i++) {
            for(int j = 0; j < 3; j++) {
                if(j == 0) {
                    rowData[i][j] = i + 1;
                }
                else if(j == 1) {
                    rowData[i][j] = rm.getListTitle().get(i);
                }
                else {
                    rowData[i][j] = rm.getListName().get(i);
                }
            }
        }
        String[] columTitle = {"순위" , "노래", "가수" };
        dtm = new DefaultTableModel(rowData, columTitle);
        
        table = new JTable(dtm);
        
        jTable1.setModel(dtm);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm;
        JTable table;
        Object[][] rowData = new Object[50][3];
        for(int i = 0; i < 50; i++) {
            for(int j = 0; j < 3; j++) {
                if(j == 0) {
                    rowData[i][j] = i + 1;
                }
                else if(j == 1) {
                    rowData[i][j] = rg.getListTitle().get(i);
                }
                else {
                    rowData[i][j] = rg.getListName().get(i);
                }
            }
        }
        String[] columTitle = {"순위" , "노래", "가수" };
        dtm = new DefaultTableModel(rowData, columTitle);
        
        table = new JTable(dtm);
        
        jTable1.setModel(dtm);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void SearchMelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMelonActionPerformed
        String str = jTextField2.getText();
        DefaultTableModel dtm;
        JTable table;
        Object[][] rowData = new Object[50][3];
        int j = 0;
        
        for(int i=0;i<50;i++){
            if(rm.getListTitle().get(i).contains(str)){
               rowData[j][0] = i+1;
               rowData[j][1] = rm.getListTitle().get(i);
               rowData[j][2] = rm.getListName().get(i);
               j++;
            }   
        }
        
        for(int i=0;i<50;i++){
            if(rm.getListName().get(i).contains(str)){
               rowData[j][0] = i+1;
               rowData[j][1] = rm.getListTitle().get(i);
               rowData[j][2] = rm.getListName().get(i);
               j++;
            }   
        }
        
        String[] columTitle = {"Rank","Title","Name"};
        dtm = new DefaultTableModel(rowData,columTitle);
        
        table = new JTable(dtm);
        
        jTable1.setModel(dtm);
    }//GEN-LAST:event_SearchMelonActionPerformed

    private void SearchGenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchGenieActionPerformed
        String str1 = jTextField2.getText();
        String str2 = jTextField1.getText();
        
        DefaultTableModel dtm;
        JTable table;
        Object[][] rowData = new Object[50][3];
        int j = 0;
        
        // 이 부분 바꾸기
        System.out.println("str1  =  " + str1.isEmpty());
        if(str1.isEmpty() == false){
            if(str2.isEmpty() == false) {
                for(int i=0;i<50;i++){
                    if(rg.getListTitle().get(i).contains(str1)){
                       rowData[j][0] = i+1;
                       rowData[j][1] = rg.getListTitle().get(i);
                       rowData[j][2] = rg.getListName().get(i);
                       j++;
                    }   
                }
            }
            else {
                for(int i=0;i<50;i++){
                    if(rg.getListTitle().get(i).contains(str1)){
                       rowData[j][0] = i+1;
                       rowData[j][1] = rg.getListTitle().get(i);
                       rowData[j][2] = rg.getListName().get(i);
                       j++;
                    }   
                }
            }
        } 
        else if(str2.isEmpty()==false){
            if(str1.isEmpty()) {
                for(int i=0;i<50;i++){
                    if(rg.getListName().get(i).contains(str2)){
                       rowData[j][0] = i+1;
                       rowData[j][1] = rg.getListTitle().get(i);
                       rowData[j][2] = rg.getListName().get(i);
                       j++;
                    }   
                }
            }
//            else {
//                for(int i=0;i<50;i++){
//                    if(rg.getListName().get(i).contains(str2)){
//                       rowData[j][0] = i+1;
//                       rowData[j][1] = rg.getListTitle().get(i);
//                       rowData[j][2] = rg.getListName().get(i);
//                       j++;
//                    }   
//                }
//            }
        }
            
            
       /* if(str1 != null && str2 != null) {
            rowData[0][0] = "0";
            rowData[0][1] = "0";
            rowData[0][2] = "0";
            for(int i=0;i<50;i++){
                if(rg.getListTitle().get(i).contains(str1)){
                   rowData[j][0] = i+1;
                   rowData[j][1] = rg.getListTitle().get(i);
                   rowData[j][2] = rg.getListName().get(i);
                   j++;
                }   
            }
        }*/
       
        
        String[] columTitle = {"Rank","Title","Name"};
        dtm = new DefaultTableModel(rowData,columTitle);
        
        table = new JTable(dtm);
        
        jTable1.setModel(dtm);
    }//GEN-LAST:event_SearchGenieActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void runMusicChart() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchGenie;
    private javax.swing.JButton SearchMelon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
